
version: "3.7"

services:
  api:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: sampleWebApi
    ports:
      - "85:5000"
    expose:
      - "5000"
    restart: always
